#! /bin/sh
# /etc/init.d/example
 
case "$1" in
  start)
    echo "Starting allskybot"
    # run application you want to start
    python /home/pi/bin/allskyBot.py &
    ;;
  stop)
    echo "Stopping allskybot"
    # kill application you want to stop
    # kill $(ps aux | grep “python /home/pi/bin/allskyBot.py” | awk '{print $2}')
    killall python
;;
  *)
    echo "Usage: /etc/init.d/$0 {start|stop}"
    exit 1
    ;;
esac
 
exit 0
